# Generated by Django 2.2 on 2020-03-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='more_about_you',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='people',
            name='favorite_color',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
